name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: 'acseshop620851653'
  CONTAINER_NAME: 'productservice'
  RESOURCE_GROUP: 'rg-eshop'
  CLUSTER_NAME: 'aks-eshop'
  DEPLOYMENT_MANIFEST_PATH: './product.yml'
  DOCKER_PATH: './DockerfileProducts.acr'

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Build and push image to ACR
        run: |
          az acr build --file ${{ env.DOCKER_PATH }} --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .
